import Head from 'next/head'
import Link from 'next/link'
import dashify from 'dashify'
import { useState } from 'react'
import { useRouter } from 'next/router'
import { PrismaClient } from '@prisma/client'
import styles from '../styles/Home.module.css'

const prisma = new PrismaClient()

export default function Home({ data }) {
    const router = new useRouter()

      /* This variable for input data */
      const [formData, setFormData] = useState(data);
      const [picture, setPicture] = useState(null)
      /* This async function to define saveMovie */
      async function saveMovie(e) {
        e.preventDefault();
        // router.push('/show')
        try {
          const allData = new FormData();
          allData.append('image', picture);
          allData.append('title', formData);
          allData.append('year', formData);
          allData.append('description', formData);

          const res = await fetch('/api/upload', {
              method: 'POST',
              body: allData,
          })
          
          const data = await res.json();
          if (!res.ok) {
              throw new Error(data.message);
          }
          setPicture(null);
        } catch (err) {
          console.error(err.message);
        }
        console.log(formData);
      };

  /* This for read data */
  return (
    <div className={styles.container}>
      <Head>
        <title>Movie List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

          {/* This form to input data */}
          <form className={styles.movieform} onSubmit={saveMovie}>
            <input 
              type="text"
              placeholder="Enter the title movie.."
              name="title" 
              onChange={e=> setFormData({ ...formData, title: e.target.value })} 
              required 
            />
            <input 
              type="number" 
              placeholder="Enter the year movie.." 
              name="year" 
              onChange={e=> setFormData({ ...formData, year: +e.target.value })} 
              required 
            />
            <input 
              type="file" 
              placeholder="Enter the year movie.." 
              name="pictures" 
              onChange={e=> setPicture(e.target.files[0] )} 
              required 
            />
            <textarea 
              name="description" 
              cols="30" 
              rows="10" 
              placeholder="Enter the description movie.." 
              onChange={e=> setFormData({ ...formData, description: e.target.value })} required 
            />
            <input 
              type="text" 
              placeholder="Enter the slug.." 
              name="slug" 
              value={dashify(formData.title ?? "")}
              disabled
              required 
            />
            <button type="submit">Add New Movie</button>
          <Link href="/show">
            <a>See All Movie</a>
          </Link>
          </form> 

      </main>
    </div>
  )
}

export async function getServerSideProps() {

  const movies = await prisma.movie.findMany()

  return {
    props: {
      data: movies 
    }
  }
}

