import Head from 'next/head';
import Link from 'next/link';
import { PrismaClient } from '@prisma/client';
import styles from '../styles/Home.module.css';

const prisma = new PrismaClient()

export default function Home({ data }) {

 
  /* This for read data */
  return (
    <div className={styles.container}>
      <Head>
        <title>Movie List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

          <ul className={styles.movielist}>
              {data.map((item) => (
                <li key={item.id}>
                  <span><strong>{item.title}</strong></span>
                  <span>{item.year}</span>
                  <Link href={`/details/${item.slug}`}>
                      <a>More About this movie</a>
                  </Link>
                  <br /><br />
                  <Link href={`/update/${item.slug}`}>
                     <a>Edit This</a>
                  </Link>
                  <br /><br />
                  <Link href="/">
                    <a>Create Movie</a>
                  </Link>
                </li>
              ))}
          </ul> 
      </main>
    </div>
  )
}

export async function getStaticProps() {

  const movies = await prisma.movie.findMany()

  return {
    props: {
      data: movies 
    }
  }
}

